<a href="https://colab.research.google.com/github/JhobanyT/BigDataRepositorio/blob/main/practica_archivo1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1 - Carga de un archivo CSV desde drive

In [1]:
import numpy as np
import pandas as pd

In [9]:
url_drive_arch1 = ("https://docs.google.com/spreadsheets/d/e/2PACX-1vS2_mvztbtzGwRP5hD-MR2iO3UZPz_DjZQKgWLwTcLPEpfAYOncaJqxDe4SZ37kvOm3QEAsuW1BD2qU/pub?gid=935185909&single=true&output=csv")
df_drive_arch1 = pd.read_csv(url_drive_arch1)
print(df_drive_arch1.shape)
df_drive_arch1.head()

(23, 4)

  nombre  edad    ciudad  ingresos
0   Juan    30      Lima      2500
1  María    28  Arequipa      3800
2   Luis    35     Cusco      4800
3    Ana    22  Trujillo      2000
4  Pedro    28  Arequipa      3200

In [8]:
url = ("https://raw.githubusercontent.com/JhobanyT/BigDataRepositorio/main/archivo_1.csv")
df = pd.read_csv(url)
print(df.shape)
df.head()

(23, 4)

  nombre  edad    ciudad  ingresos
0   Juan    30      Lima      2500
1  María    28  Arequipa      3800
2   Luis    35     Cusco      4800
3    Ana    22  Trujillo      2000
4  Pedro    28  Arequipa      3200

In [6]:
df.columns.values

array(['nombre', 'edad', 'ciudad', 'ingresos'], dtype=object)

Obtenemos la suma total de ingresos

In [21]:
suma_ingresos = df['ingresos'].sum()
print("La suma de los inresos es: ", suma_ingresos)

La suma de los inresos es:  76180

Promedio de edades

In [20]:
promedio_edad = df['edad'].mean()
print("El promedio de la edad de las persona es:", int(promedio_edad))

El promedio de la edad de las persona es: 31

Obtenemos las personas que trabajan en arequipa

In [37]:
personas_arequipa = df[df['ciudad'] == "Arequipa"].sum
personas_arequipa.iloc[:, [0,2]]

      nombre    ciudad
1      María  Arequipa
4      Pedro  Arequipa
10  Gabriela  Arequipa
15    Javier  Arequipa
21      José  Arequipa

Obtenemos Los ingresos por ciudad

In [38]:
ingreso_ciudad = df.groupby('ciudad')['ingresos'].mean().astype(int)
ingreso_ciudad

ciudad
Arequipa    4040
Cusco       2975
Juliaca     4990
Lima        3366
Puno        1300
Trujillo    2520
Name: ingresos, dtype: int64

La persona más joven

In [50]:
# persona mas joven
persona_joven = df.nsmallest(1, 'edad')
print(f"La persona mas joven es: {persona_joven['nombre']}")

La persona mas joven es: 11    Micaela
Name: nombre, dtype: object

La persona más mayor

In [45]:
# persona mas mayor
persona_mayor = df.nlargest(1, 'edad')
print(f"La persona mas mayor es: {persona_mayor['nombre']}")

La persona mas mayor es: 5    Leonel
Name: nombre, dtype: object

Trabajadores por ciudad

In [57]:
# primera opcion
trabajadores_ciudades = df.groupby('ciudad')['nombre'].count()
trabajadores_ciudades

ciudad
Arequipa    5
Cusco       4
Juliaca     2
Lima        6
Puno        1
Trujillo    5
Name: nombre, dtype: int64

In [64]:
# segunda opcion
personas_ciudades = df['ciudad'].value_counts()
personas_ciudades

Lima        6
Arequipa    5
Trujillo    5
Cusco       4
Juliaca     2
Puno        1
Name: ciudad, dtype: int64

Orden de personas con mayor edad

In [81]:
# Primera opcion
edad_orden = df.nlargest(len(df["edad"]),'edad')
edad_orden

       nombre  edad    ciudad  ingresos
5      Leonel    64   Juliaca      4980
22      Willy    55      Puno      1300
2        Luis    35     Cusco      4800
19    Ricardo    35      Lima      4400
21       José    34  Arequipa      4200
10   Gabriela    33  Arequipa      4000
15     Javier    32  Arequipa      5000
6       Laura    31      Lima      4200
17     Manuel    31  Trujillo      2700
14     Lorena    30      Lima      3800
0        Juan    30      Lima      2500
8       Sofía    29  Trujillo      2900
16    Daniela    29      Lima      2700
1       María    28  Arequipa      3800
18   Fernanda    28     Cusco      2100
4       Pedro    28  Arequipa      3200
9      Andrés    27      Lima      2600
13  Valentina    26  Trujillo      3500
7      Carlos    25     Cusco      1800
12      Diego    24     Cusco      3200
20      Lucía    23  Trujillo      1500
3         Ana    22  Trujillo      2000
11    Micaela    21   Juliaca      5000

In [83]:
# Segunda opción
edad_orden = df.sort_values("edad", ascending=False)
edad_orden

       nombre  edad    ciudad  ingresos
5      Leonel    64   Juliaca      4980
22      Willy    55      Puno      1300
2        Luis    35     Cusco      4800
19    Ricardo    35      Lima      4400
21       José    34  Arequipa      4200
10   Gabriela    33  Arequipa      4000
15     Javier    32  Arequipa      5000
6       Laura    31      Lima      4200
17     Manuel    31  Trujillo      2700
14     Lorena    30      Lima      3800
0        Juan    30      Lima      2500
8       Sofía    29  Trujillo      2900
16    Daniela    29      Lima      2700
1       María    28  Arequipa      3800
18   Fernanda    28     Cusco      2100
4       Pedro    28  Arequipa      3200
9      Andrés    27      Lima      2600
13  Valentina    26  Trujillo      3500
7      Carlos    25     Cusco      1800
12      Diego    24     Cusco      3200
20      Lucía    23  Trujillo      1500
3         Ana    22  Trujillo      2000
11    Micaela    21   Juliaca      5000

TAREA

In [90]:
ingresos_mayores_30 = df[df["edad"] > 30]["ingresos"].mean()
print(f"El promedio de ingresos de las personas mayores a 30 años es: {int(ingresos_mayores_30)}")

El promedio de ingresos de las personas mayores a 30 años es: 3953

Promedio de ingresos por ciudades

In [89]:
ingresos_ciudades = df.groupby('ciudad')['ingresos'].sum()
ingresos_ciudades

ciudad
Arequipa    20200
Cusco       11900
Juliaca      9980
Lima        20200
Puno         1300
Trujillo    12600
Name: ingresos, dtype: int64

Personas con el ingreso mas alto

In [94]:
persona_mayor_ingreso = df.nlargest(1, 'ingresos')
print(f"La persona con el mayor ingreso es: {persona_mayor_ingreso['nombre']}")

La persona con el mayor ingreso es: 11    Micaela
Name: nombre, dtype: object